[package]
name = "insights"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
actix-web = "4.0"
askama = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }